config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  resources :students, :study_groups, :courses
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'register' => 'students#new'

  root 'static_pages#landing'#'application#hello'
 
  

end

app/models/study_group.rb
class StudyGroup < ActiveRecord::Base
	#One-to-many relationship between StudyGroup and meeting_times
	has_many :meeting_times

	#Many-to-one rel. between study_group and course
	belongs_to :course
	#validates_presence_of :course
	#Rich many-to-many rel. between studygroup and student
	has_many :members
	has_many :students, :through => :member

	#Rich many-to-one rel. between studygroup and student where studen is the creator
	has_one :creator
	has_one :student, :through => :creator




	#Content validations
	#validates :course_id, presence: true
	validates :gname, presence: true
	validates :location, presence: true
	validates_uniqueness_of :gname
end

app/controllers/study_groups_controller.rb
class StudyGroupsController < ApplicationController
  before_action :set_study_group, only: [:show, :edit, :update, :destroy]

  # GET /study_groups
  # GET /study_groups.json
  def index
    @study_groups = StudyGroup.all
  end

  # GET /study_groups/1
  # GET /study_groups/1.json
  def show
  end

  # GET /study_groups/new
  def new
    @study_group = StudyGroup.new
  end

  # GET /study_groups/1/edit
  def edit
  end

  # POST /study_groups
  # POST /study_groups.json
  def create
    @study_group = StudyGroup.new(study_group_params)

    respond_to do |format|
      if @study_group.save
        format.html { redirect_to @study_group, notice: 'Study group was successfully created.' }
        format.json { render :show, status: :created, location: @study_group }
      else
        format.html { render :new }
        format.json { render json: @study_group.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /study_groups/1
  # PATCH/PUT /study_groups/1.json
  def update
    respond_to do |format|
      if @study_group.update(study_group_params)
        format.html { redirect_to @study_group, notice: 'Study group was successfully updated.' }
        format.json { render :show, status: :ok, location: @study_group }
      else
        format.html { render :edit }
        format.json { render json: @study_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /study_groups/1
  # DELETE /study_groups/1.json
  def destroy
    @study_group.destroy
    respond_to do |format|
      format.html { redirect_to study_groups_url, notice: 'Study group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_study_group
      @study_group = StudyGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def study_group_params
      params.require(:study_group).permit(:course_id, :gname, :description, :location)
    end
end

app/helpers/study_groups_helper.rb
module StudyGroupsHelper
end

app/views/study_groups/_form.html.erb
<%= form_for(@study_group) do |f| %>
  <% if @study_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@study_group.errors.count, "error") %> prohibited this study_group from being saved:</h2>

      <ul>
      <% @study_group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- <div class="field">
    <%= f.hidden_field :course_id, value: nil %><br>
    <%= f.submit "Remove", class: "btn" %>
  </div> --> 
  
  <div class="field">
    <%= f.label :course_id %><br>
    <%= f.number_field :course_id %>
  </div>

  <div class="field">
    <%= f.label "Name" %><br>
    <%= f.text_field :gname %>
  </div>
  <div class="field">
    <%= f.label "Description" %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label "Location" %><br>
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>





<% end %>

app/views/study_groups/edit.html.erb
<h1>Editing Study Group</h1>

<%= render 'form' %>

<%= link_to 'Show', @study_group %> |
<%= link_to 'Back', study_groups_path %>

app/views/study_groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Study Groups</h1>

<table>
  <thead>
    <tr>
      <th>Course</th>
      <th>Gname</th>
      <th>Description</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @study_groups.each do |study_group| %>
      <tr>
        <td><%= study_group.course_id %></td>
        <td><%= study_group.gname %></td>
        <td><%= study_group.description %></td>
        <td><%= study_group.location %></td>
        <td><%= link_to 'Show', study_group %></td>
        <td><%= link_to 'Edit', edit_study_group_path(study_group) %></td>
        <td><%= link_to 'Destroy', study_group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Study group', new_study_group_path %>

app/views/study_groups/new.html.erb
<h1>New Study Group</h1>

<%= render 'form' %>

<%= link_to 'Back', study_groups_path %>

app/views/study_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Course:</strong>
  <%= @study_group.course_id %>
</p>

<p>
  <strong>Gname:</strong>
  <%= @study_group.gname %>
</p>

<p>
  <strong>Description:</strong>
  <%= @study_group.description %>
</p>

<p>
  <strong>Location:</strong>
  <%= @study_group.location %>
</p>

<%= link_to 'Edit', edit_study_group_path(@study_group) %> |
<%= link_to 'Back', study_groups_path %>