config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  resources :students, :study_groups, :courses
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'register' => 'students#new'

  root 'static_pages#landing'#'application#hello'
 
  

end

app/models/student.rb
class Student < ActiveRecord::Base
	#Rich m-to-m rel. between student and studygroup
	has_many :members
	has_many :study_groups, :through => :member

	#Rich one-to-many rel. between student and studygroup/course where student is the creator
	has_many :creators
	has_many :study_groups, :through => :creator

	validates :sname, presence: true
	validates :email, presence: true
	validates :password_digest, presence: true
	validates_uniqueness_of :email

    has_secure_password
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  def login
    
    render :nothing => true
  end

  
  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
      @groups = []
      @members = Member.where(student_id: @student.id)
      @members.each do |m|
          @groups << StudyGroup.find(m.study_group_id)
      end
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        log_in @student
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:sname, :email, :password, :password_confirmation)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Name" %><br>
    <%= f.text_field :sname %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label "Password" %><br>
    <%= f.text_field :pwd %>
  </div>
  <div class="field">
    <%= f.label :token %><br>
    <%= f.text_field :token %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Students</h1>

<table>
  <thead>
    <tr>
      <th>Sname</th>
      <th>Email</th>
      <th>Pwd</th>
      <th>Token</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.sname %></td>
        <td><%= student.email %></td>
        <td><%= student.pwd %></td>
        <td><%= student.token %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
      <div class="col-md-6 col-md-offset-3">
          <%= form_for(@student) do |f| %>
              <%= f.label :sname, "Name" %>
              <%= f.text_field :sname %>

              <%= f.label :email %>
              <%= f.email_field :email %>

              <%= f.label :password, "Password" %>
              <%= f.password_field :password %>

              <%= f.label :password_confirmation, "Confirmation" %>
              <%= f.password_field :password_confirmation %>

              <%= f.submit "Create my account", class: "btn btn-primary" %>
          <% end %>
      </div>
</div>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<div class="left jumbotron">
    <h1><%=@student.sname%></h1>
</div>

<h2>My Groups</h2>
<div class="row">
    <div class="col-md-6">
        <div class="row">
            <div class="col-md-2">Name</div>
            <div class="col-md-2">Description</div>
        </div>
        <% @groups.each do |g| %>
            <div class="row">
                <div class="col-md-2"><%=g.gname%></p> </div>
                <div class="col-md-2"><%=g.description%></p></div>
            </div>

        <% end %>
    </div>
    <div class="col-md-3">
        <div class="row">
            <%= link_to "Join a group", new_member_path%>
        </div>
        <div class="row">
            <%= link_to "Create a group", courses_path%> 
</div>